include(${CGET_CORE_DIR}.cget/core.cmake)

CGET_HAS_DEPENDENCY(OpenCV GITHUB opencv/opencv VERSION 3.4.0
  OPTIONS
  -DENABLE_PRECOMPILED_HEADERS:BOOL=OFF
  -DBUILD_WITH_STATIC_CRT:BOOL=OFF
  -DBUILD_opencv_java:BOOL=OFF
  -DBUILD_opencv_calib3d:BOOL=ON
  -DBUILD_opencv_videoio:BOOL=ON
  -DBUILD_opencv_video:BOOL=ON
  -DBUILD_opencv_highgui:BOOL=ON
  -DBUILD_opencv_python:BOOL=OFF
  -DBUILD_opencv_python2:BOOL=OFF
  -DBUILD_opencv_python3:BOOL=OFF
  -DBUILD_FAT_JAVA_LIB:BOOL=OFF
  -DBUILD_TESTS:BOOL=OFF
  -DBUILD_PERF_TESTS:BOOL=OFF
  -DBUILD_PACKAGE:BOOL=OFF
  -DBUILD_DOCS:BOOL=OFF
  -DBUILD_opencv_apps:BOOL=OFF
  -BUILD_SHARED_LIBS:BOOL=ON
  -DANDROID:BOOL=OFF
  -DWITH_VTK:BOOL=OFF
  -DWITH_WIN32UI:BOOL=OFF
  -DWITH_QT:BOOL=ON
  -DWITH_CUDA:BOOL=ON
  -DWITH_CUFFT:BOOL=ON
  -DWITH_CUBLAS:BOOL=ON
  -DCUDA_ARCH_BIN="3.5 6.1"
  -DCUDA_HOST_COMPILER=/usr/bin/gcc-6
  -DCUDA_NVCC_FLAGS=--expt-relaxed-constexpr
  -DCUDA_GENERATION:STRING=Pascal
  -DBUILD_ZLIB:BOOL=OFF )

CGET_HAS_DEPENDENCY(survive GITHUB jdavidberger/libsurvive COMMIT_ID fe88ef57cff4971664b252cb9def6a5ddcc4276d LIBRARY survive)
CGET_HAS_DEPENDENCY(Poco GITHUB pocoproject/poco VERSION poco-1.8.1-release COMPONENTS Foundation Util XML)
CGET_HAS_DEPENDENCY(sba GITHUB balintfodor/sba COMMIT_ID 8f774bf LIBRARY sba)
